### ISSUE TITLE
Why is apply_rotary_pos_emb not used in this repo code?

### ISSUE THREAD

**Issue by morestart** [Aveygo/VisionDiff#1]

**Comment by Aveygo** [comment]
Wasn't sure how ROPE performs in images (only found https://arxiv.org/pdf/2403.13298) so in a rush I borrowed code from DiT and forgot to add positional encoding in the patchify function - Fixed now by using https://github.com/lucidrains/rotary-embedding-torch. Fixed in https://github.com/Aveygo/VisionDiff/pull/2
